<?php

namespace Database\Seeders;

use App\Models\Pays;
use Illuminate\Database\Seeder;

// Ce seeder sert à alimenter le référentiel des 193 pays membres de l'ONU.
// Il fonctionne avec la liste officielle des États membres (ordre alphabétique).
// Dans le but de fournir une liste complète pour la sélection du pays de résidence (locale et diaspora).
// Pour régler la standardisation des pays et marquer la Côte d'Ivoire par défaut.
class PaysSeeder extends Seeder
{
    // Ce code sert à insérer ou mettre à jour la liste complète des 193 pays de l'ONU en base de données.
    // Il fonctionne avec le tableau $paysList et la méthode de mise à jour en masse Pays::upsert().
    // Dans le but de peupler la table 'pays' et de définir la Côte d'Ivoire comme valeur par défaut.
    // Pour régler la disponibilité des données géographiques internationales.
    public function run(): void
    {
        // Liste des 193 États membres de l'ONU
        $paysList = [
            "Afghanistan",
            "Afrique du Sud",
            "Albanie",
            "Algérie",
            "Allemagne",
            "Andorre",
            "Angola",
            "Antigua-et-Barbuda",
            "Arabie saoudite",
            "Argentine",
            "Arménie",
            "Australie",
            "Autriche",
            "Azerbaïdjan",
            "Bahamas",
            "Bahreïn",
            "Bangladesh",
            "Barbade",
            "Belgique",
            "Belize",
            "Bénin",
            "Bhoutan",
            "Biélorussie",
            "Birmanie",
            "Bolivie",
            "Bosnie-Herzégovine",
            "Botswana",
            "Brésil",
            "Brunei",
            "Bulgarie",
            "Burkina Faso",
            "Burundi",
            "Cap-Vert",
            "Cambodge",
            "Cameroun",
            "Canada",
            "Chili",
            "Chine",
            "Chypre",
            "Colombie",
            "Comores",
            "Congo",
            "Corée du Nord",
            "Corée du Sud",
            "Costa Rica",
            "Côte d'Ivoire",
            "Croatie",
            "Cuba",
            "Danemark",
            "Djibouti",
            "Dominique",
            "Égypte",
            "Émirats arabes unis",
            "Équateur",
            "Érythrée",
            "Espagne",
            "Estonie",
            "Eswatini",
            "États-Unis",
            "Éthiopie",
            "Fidji",
            "Finlande",
            "France",
            "Gabon",
            "Gambie",
            "Géorgie",
            "Ghana",
            "Grèce",
            "Grenade",
            "Guatemala",
            "Guinée",
            "Guinée-Bissau",
            "Guinée équatoriale",
            "Guyana",
            "Haïti",
            "Honduras",
            "Hongrie",
            "Îles Marshall",
            "Îles Salomon",
            "Inde",
            "Indonésie",
            "Irak",
            "Iran",
            "Irlande",
            "Islande",
            "Israël",
            "Italie",
            "Jamaïque",
            "Japon",
            "Jordanie",
            "Kazakhstan",
            "Kenya",
            "Kirghizistan",
            "Kiribati",
            "Koweït",
            "Laos",
            "Lesotho",
            "Lettonie",
            "Liban",
            "Libéria",
            "Libye",
            "Liechtenstein",
            "Lituanie",
            "Luxembourg",
            "Macédoine du Nord",
            "Madagascar",
            "Malaisie",
            "Malawi",
            "Maldives",
            "Mali",
            "Malte",
            "Maroc",
            "Maurice",
            "Mauritanie",
            "Mexique",
            "Micronésie",
            "Moldavie",
            "Monaco",
            "Mongolie",
            "Monténégro",
            "Mozambique",
            "Namibie",
            "Nauru",
            "Népal",
            "Nicaragua",
            "Niger",
            "Nigéria",
            "Norvège",
            "Nouvelle-Zélande",
            "Oman",
            "Ouganda",
            "Ouzbékistan",
            "Pakistan",
            "Palaos",
            "Panama",
            "Papouasie-Nouvelle-Guinée",
            "Paraguay",
            "Pays-Bas",
            "Pérou",
            "Philippines",
            "Pologne",
            "Portugal",
            "Qatar",
            "République centrafricaine",
            "République démocratique du Congo",
            "République dominicaine",
            "Roumanie",
            "Royaume-Uni",
            "Russie",
            "Rwanda",
            "Saint-Christophe-et-Niévès",
            "Sainte-Lucie",
            "Saint-Marin",
            "Saint-Vincent-et-les-Grenadines",
            "Salvador",
            "Samoa",
            "São Tomé-et-Príncipe",
            "Sénégal",
            "Serbie",
            "Seychelles",
            "Sierra Leone",
            "Singapour",
            "Slovaquie",
            "Slovénie",
            "Somalie",
            "Soudan",
            "Soudan du Sud",
            "Sri Lanka",
            "Suède",
            "Suisse",
            "Suriname",
            "Syrie",
            "Tadjikistan",
            "Tanzanie",
            "Tchad",
            "Tchéquie",
            "Thaïlande",
            "Timor oriental",
            "Togo",
            "Tonga",
            "Trinité-et-Tobago",
            "Tunisie",
            "Turkménistan",
            "Turquie",
            "Tuvalu",
            "Ukraine",
            "Uruguay",
            "Vanuatu",
            "Venezuela",
            "Viêt Nam",
            "Yémen",
            "Zambie",
            "Zimbabwe",
        ];

        $now = now();
        $data = [];

        // On parcourt chaque pays pour préparer les données d'insertion et marquer la Côte d'Ivoire par défaut (is_default = true)
        foreach ($paysList as $nom) {
            $isDefault = ($nom === "Côte d'Ivoire");
            $data[] = [
                'nom' => $nom,
                'code_iso' => null,
                'is_default' => $isDefault,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        // Insère en masse ou met à jour si le pays existe déjà (évite les doublons et permet de relancer le seeder sans erreur)
        Pays::upsert($data, ['nom'], ['is_default', 'updated_at']);
    }
}
